site_name: Railtracks Docs
site_url: https://railtownai.github.io/railtracks/
site_description: "Railtracks is a framework for building LLM-powered agents and applications."

repo_name: railtracks
repo_url: https://github.com/RailtownAI/railtracks/



theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg

  custom_dir: docs/overrides

  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.prefetch
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - content.code.highlight
    - content.code.annotate

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span

extra_css:
  - css/extra.css

extra:
  generator: false

nav:
  - Home: index.md

  - Quickstart: quickstart/quickstart.md

  - Background:
      - Agents: background/agents.md
      - Tools: background/tools.md
      - RAG: background/RAG.md
      - Async/Await: background/async_await.md
  
  - Tutorials:
      - Building your first agent: tutorials/byfa.md
      - Running your first agent: tutorials/ryfa.md
      - RAG system: tutorials/rag_tutorial.md

  - Tools + MCP:
      - Equip your LLMs: tools_mcp/tools_mcp.md
      - MCP:
          - Model Context Protocol: tools_mcp/mcp/mcp.md
          - Using MCP: tools_mcp/mcp/MCP_tools_in_RT.md
          - Creating an MCP Server: tools_mcp/mcp/RTtoMCP.md

      - Tools:
          - What is a Tool: tools_mcp/tools/tools.md
          - Functions as Tools: tools_mcp/tools/functions_as_tools.md
          - Agents as Tools: tools_mcp/tools/agents_as_tools.md

      - Integrations:
          - Notion: tools_mcp/guides/notion.md
          - Github: tools_mcp/guides/github.md
          - Python Sandbox: tools_mcp/guides/python_sandbox.md
          - Shell Bash: tools_mcp/guides/shell_bash.md
          - Slack: tools_mcp/guides/slack.md
          - Web Search: tools_mcp/guides/websearch_integration.md
      - RAG: tools_mcp/RAG.md
  - Human in the Loop:
      - Overview: human_in_the_loop/overview.md
      - Local Chat UI: human_in_the_loop/local_chat_ui.md
      - Human in the Loop: human_in_the_loop/hil.md
  - Observability:
      - Visualization: observability/visualization.md
      - Logging: observability/logging.md
      - Broadcasting: observability/broadcasting.md
      - Error Handling: observability/error_handling.md

  - LLM Support:
      - Supported Providers: llm_support/providers.md
      - Prompts and Context Injection: llm_support/prompts.md
      
  # - Deployments:
  #     - Docker: deployments/docker.md

  - Advanced Usage:
      - Session: advanced_usage/session.md
      - Context: advanced_usage/context.md
      # - Configuration: advanced_usage/config.md

  # - Samples:
  #     - samples/index.md

  # - System Internals:
  #     - Overview: system_internals/overview.md
  #     - Core Concepts: system_internals/concepts.md
  #     - Node Abstraction: system_internals/node.md
  #     - Session Management: system_internals/session.md
  #     - PubSub Messaging: system_internals/pubsub.md
  #     - Coordinator Orchestration: system_internals/coordinator.md

  - API Reference: api_reference/railtracks.html



    