name: Publish to Azure Artifacts on Release

on:
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write # Required for Azure authentication

env:
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit

      - name: Normalize version number
        run: |
          VERSION_CLEANED=${{ env.RELEASE_TAG }}
          VERSION_CLEANED=${VERSION_CLEANED#v}  # Remove 'v' if present
          echo "VERSION_CLEANED=$VERSION_CLEANED" >> $GITHUB_ENV
          echo "Publishing version: $VERSION_CLEANED"

      - name: Update version in __init__.py
        run: |
          sed -i -E 's/__version__ = ".+"/__version__ = "'"$VERSION_CLEANED"'"/' src/requestcompletion/__init__.py
          echo "Updated __init__.py to version $VERSION_CLEANED"

      - name: Build and Publish with Flit
        env:
          FLIT_INDEX_URL: 'https://pkgs.dev.azure.com/railtownai/ML/_packaging/railtownai_rc/pypi/upload/' # Private Package URL
          FLIT_USERNAME: 'AZURE'
          FLIT_PASSWORD: ${{ secrets.AZURE_ARTIFACTS_PAT }}
        run: |
          flit publish
